### ISSUE TITLE
Migrate adapty-flutter android to Built-in Kotlin

### ISSUE THREAD

**Issue by schufty** [adaptyteam/AdaptySDK-Flutter#192]
`adapty-flutter`'s android build applies the Kotlin Gradle Plugin (KGP). But Android Gradle Plugin 9.0 has removed support for KGP, and I'm getting warnings from `flutter build appbundle` that future versions of Flutter will fail if any plugins continue to use KGP. Here's the warning:

```
WARNING: Your app uses the following plugins that apply Kotlin Gradle Plugin (KGP): adapty_flutter, device_info_plus, flutter_email_sender, image_editor_common, share_plus
Future versions of Flutter will fail to build if your app uses plugins that apply KGP.

Please check the changelogs of these plugins and upgrade to a version that supports Built-in Kotlin.
If no such version exists, report the issue to the plugin. If necessary, here is a guide on filing
an issue against a plugin: https://docs.flutter.dev/release/breaking-changes/migrate-to-built-in-kotlin/for-app-developers#report-incompatible-kotlin-gradle-plugin-usage-to-plugin-authors

If you are a plugin author, please migrate your plugin to Built-in Kotlin using this guide: https://docs.flutter.dev/release/breaking-changes/migrate-to-built-in-kotlin/for-plugin-authors
```
The warning includes a link to a guide for plugin authors to migrate to Flutter's Built-in Kotlin.

Please migrate `adapty_flutter` ot use built-in Kotlin.

**Comment by greatsam4sure** [comment]
Flutter 3.44.1 does not even compile with adapty_flutter 3.17.0 the same warm as in above. The other plugin such as share_plus have updated their plugin using the recent version solve the problem. I have to remove adapty_flutter from my yaml file for my app to run despite adapty_flutter 3.17.0 was just release 15days as of today. I will appreciate a quick fix, as my app is at the point of release after close testing

**Comment by vladd-g** [comment]
Hi @schufty @greatsam4sure, thank you for the report! We're taking a look.

**Comment by vladd-g** [comment]
@greatsam4sure could you check whether [this](https://github.com/adaptyteam/AdaptySDK-Flutter/issues/189#issuecomment-4661940220) fixes the compilation for you?

**Comment by schufty** [comment]
I can confirm that the pub-cache workaround resolves the mismatched JVM version compilation error.

**Comment by greatsam4sure** [comment]
This work around does not solve my problem. I am using Flutter 3.44.0 and dart 3.12.0. I have to comment out the plugin to be able to compile my app

**Comment by mehmetgencdal** [comment]
Same error here. Tried many things but couldn't fix.

EDIT: pub-cache solution fixed the problem temp @vladd-g

**Comment by vladd-g** [comment]
Fixed in [3.17.1](https://github.com/adaptyteam/AdaptySDK-Flutter/releases/tag/3.17.1)
