### ISSUE TITLE
Compilation error for Xcode before 14.3

### ISSUE THREAD

**Issue by johnmartel** [adaptyteam/AdaptySDK-Flutter#100]
Version:

*pubspec.yaml*
adapty_flutter: 2.9.0

*Podfile.lock*
- Adapty (2.9.1)
  - adapty_flutter (2.9.0):
    - Adapty (= 2.9.1)
    - Flutter

When running a fresh Flutter iOS build on CI, I get the following compilation error:

> Failed to build iOS app
> Swift Compiler Error (Xcode): Reference to property 'apiKeyPrefix' in closure requires explicit use of 'self' to make capture > semantics explicit
> /Users/runner/work/.../ios/Pods/Adapty/Sources/StoreKit/SKProductsManager.swift:115:72

I'm running on this [GitHub runner](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md), so using XCode 14.2.

**Comment by johnmartel** [comment]
My currently working build uses adapty_flutter: 2.7.1.

**Comment by x401om** [comment]
Hi, @johnmartel! We had an issue in the native sdk which prevented to build with Xcodes prior to 14.3. It is already fixed and I suppose we will update the Adapty-Flutter pretty soon.

**Comment by johnmartel** [comment]
This explains why I do not see this issue locally with XCode 14.3. Thanks, we'll be looking forward to the released fix.

**Comment by burhanrashid52** [comment]
@x401om When can we expect the new release with this fix ? Our iOS CI pipeline is stuck because of this issue.
